### ISSUE TITLE
Ingest Pipelines - Sync up with ES main branch

### ISSUE THREAD

**Issue by mashhurs** [elastic/logstash-filter-elastic_integration#118]
### Description
Currently, our [BK pipeline job is failing](https://buildkite.com/elastic/logstash-filter-elastic-integration-build/builds/48#018d1df1-68ce-44ce-a248-c5fe9e6dde22) due to recent [ES source change](https://github.com/elastic/elasticsearch/pull/104500/files). We need to update Elastic Integration plugin `EventProcessorBuilder.java:240` to apply this change.

**Comment by yaauie** [comment]
Blocked by elastic/elasticsearch#105163 and elastic/elasticsearch#105165
