### ISSUE TITLE
Add `elastic_integration` plugin to support matrix

### ISSUE THREAD

**Issue by mashhurs** [elastic/logstash-filter-elastic_integration#152]
### Description
[The guide](https://www.elastic.co/guide/en/logstash/current/plugins-filters-elastic_integration.html#_getting_help_136) mentions the plugin under Enterprise subscription support but it cannot be found in [support matrix](https://www.elastic.co/support/matrix#logstash_plugins). We need to clarify and add it to support matrix.

**Comment by flexitrev** [comment]
Added

**Comment by mashhurs** [comment]
Covered by https://github.com/elastic/logstash-filter-elastic_integration/issues/193
