### ISSUE TITLE
Add `x-elastic-product-origin` headers to all Logstash requests to Elasticsearch

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash-filter-elastic_integration#183]
The Logstash Elasticsearch elastic integration filter plugin makes a number of HTTP requests.

* Investigate the places where HTTP requests are made to Elasticsearch in this plugin
* Add the `x-elastic-product-origin` header to each of those requests.

**Comment by robbavey** [comment]
Updated to correct the header name to x-elastic-product-origin

**Comment by donoghuc** [comment]
Shipped in [0.1.17](https://github.com/elastic/logstash-filter-elastic_integration/releases/tag/v0.1.17)
